package org.utkuozdemir.watchdist.type;

public enum WindowType {
    MAIN, WATCH_POINTS, ADD_NEW_WATCH_POINT, ADD_NEW_SOLDIER, ADMINISTRATION, WATCH_DISTRIBUTION, WATCH_VALUES,
    APP_PASSWORD, RESET_DB_PASSWORD, SET_PASSWORDS, CHANGE_APP_PASSWORD, CHANGE_DB_RESET_PASSWORD,
    SET_EXCEL_TEMPLATE_PATH, LANGUAGE_SELECTION, SET_INITIAL_VALUES, NOTES
}
