package tsk.jgnk.watchdist;

public enum AppWindow {
	MAIN, WATCH_POINTS, ADD_NEW_WATCH_POINT, ADD_NEW_SOLDIER, ADMINISTRATION, WATCH_DISTRIBUTION, WATCH_VALUES,
	APP_PASSWORD, RESET_DB_PASSWORD, SET_PASSWORDS
}
